# Generated by Django 4.1.5 on 2023-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Selecione a categoria da ordem de serviço', max_length=250, null=True),
        ),
    ]
