# Generated by Django 4.1.5 on 2023-02-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0003_alter_category_name_alter_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='neworder.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='real_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='neworder.realstateagency'),
        ),
    ]
