# Generated by Django 4.1.5 on 2023-04-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neworder', '0006_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='cpf',
        ),
    ]
